FROM	arm32v6/alpine:latest

MAINTAINER	Gaetan Cambier "Gaetan@Cambier.org"

EXPOSE	53/tcp 53/udp

ENV	BIND_USER=named \
	DATA_DIR=/data

RUN	apk add --no-cache bind 
RUN	mkdir -m 0755 -p /var/run/named  
RUN	chown -R root:named /var/run/named

VOLUME ["/data"]

COPY entrypoint.sh /sbin/entrypoint.sh
RUN chmod 755 /sbin/entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/named"]
